name: PR Visual Regression Test
on:
  workflow_run:
    workflows: [PR Build]
    types:
      - completed
jobs:
  pr-visual-regression-test:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    # This workflow intentionally does not use ubuntu-latest.
    # An updated image could generate different snapshots, so we should explicitly update the image version.
    runs-on: ubuntu-22.04
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - name: Get PR Event
        id: get-pr-event
        uses: potiuk/get-workflow-origin@v1_3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          sourceRunId: ${{github.event.workflow_run.id}}
      - name: Find Comment
        id: find-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{steps.get-pr-event.outputs.pullRequestNumber}}
          comment-author: 'github-actions[bot]'
          body-includes: ğŸ¤– Clarity Visual Regression Test Bot
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{steps.find-comment.outputs.comment-id}}
          issue-number: ${{steps.get-pr-event.outputs.pullRequestNumber}}
          body: |
            ğŸ‘‹ @${{github.event.sender.login}},

            * ğŸ™ The Clarity team thanks you for opening a pull request
            * â³ The visual regression test for this PR has started
            * ğŸ“« I'll update this comment when the test has finished

            Thank you,

            ğŸ¤– Clarity Visual Regression Test Bot
          edit-mode: replace
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{steps.get-pr-event.outputs.sourceHeadRepo}}
          ref: ${{steps.get-pr-event.outputs.sourceHeadBranch}}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Download Docs Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: docs
          path: dist/docs
          workflow: ${{github.event.workflow_run.workflow_id}}
          run_id: ${{github.event.workflow_run.id}}
      - name: Discover Stories
        run: npm run ts-node -- ./scripts/write-story-list.ts
      - name: Update VRT Snapshots
        run: npx playwright test --update-snapshots
      - name: Push Changes if Needed
        id: push-changes
        run: |
          upstream=https://github.com/${{github.repository}}.git
          updateBranchName=vrt-update/pr-${{steps.get-pr-event.outputs.pullRequestNumber}}

          git add .

          if git diff-index --quiet HEAD
          then
            git push $upstream -d $updateBranchName || echo "branch doesn't exit"

            echo "status=clean" >> $GITHUB_OUTPUT
          else
            git checkout -b $updateBranchName
            git config user.name "GitHub"
            git config user.email "noreply@github.com"
            git commit --message 'chore: update vrt snapshots for `${{steps.get-pr-event.outputs.sourceHeadBranch}}`'
            git push --set-upstream $upstream $updateBranchName --force

            echo "status=dirty" >> $GITHUB_OUTPUT
            echo "update-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          fi
      - name: Update Comment if Changes Needed
        if: ${{steps.push-changes.outputs.status == 'dirty'}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{steps.find-comment.outputs.comment-id}}
          issue-number: ${{steps.get-pr-event.outputs.pullRequestNumber}}
          body: |
            ğŸ‘‹ @${{github.event.sender.login}},

            * ğŸ˜­ The visual regression test for this PR has failed due to modified visual snapshots
            * ğŸ—’ Please see the updated visual snapshots in this commit: https://github.com/${{github.repository}}/commit/${{steps.push-changes.outputs.update-sha}}

            If these changes are intended and correct, please cherry-pick the above commit to the PR.

            ```bash
            git checkout ${{steps.get-pr-event.outputs.sourceHeadBranch}}
            git fetch https://github.com/${{github.repository}}.git ${{steps.push-changes.outputs.update-sha}}
            git cherry-pick ${{steps.push-changes.outputs.update-sha}}
            git push
            ```

            Thank you,

            ğŸ¤– Clarity Visual Regression Test Bot
          edit-mode: replace
      - name: Update Comment if Changes Not Needed
        if: ${{steps.push-changes.outputs.status == 'clean'}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{steps.find-comment.outputs.comment-id}}
          issue-number: ${{steps.get-pr-event.outputs.pullRequestNumber}}
          body: |
            ğŸ‘‹ @${{github.event.sender.login}},

            * ğŸ™ The Clarity team thanks you for opening a pull request
            * ğŸ‰ The visual regression test for this PR has succeeded

            Thank you,

            ğŸ¤– Clarity Visual Regression Test Bot
          edit-mode: replace
      - name: Update Comment if Error
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{steps.find-comment.outputs.comment-id}}
          issue-number: ${{steps.get-pr-event.outputs.pullRequestNumber}}
          body: |
            ğŸ‘‹ @${{github.event.sender.login}},

            * ğŸ™ The Clarity team thanks you for opening a pull request
            * ğŸ˜­ The visual regression test for this PR has failed due to a runtime error
            * ğŸ—’ Please check out the [test log](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
            * ğŸ– You can always follow up here. If you're a VMware employee, you can also reach us on our [internal #clarity-support Slack channel](https://vmware-clarity.slack.com/archives/C0JF8D2LB)

            Thank you,

            ğŸ¤– Clarity Visual Regression Test Bot
          edit-mode: replace
      - name: Fail if Changes Needed
        if: ${{steps.push-changes.outputs.status == 'dirty'}}
        run: |
          echo "Please see the comment on your PR from Clarity Visual Regression Test Bot."
          exit 1
